//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCOyun.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Uye
    {
        public int id { get; set; }
        public Nullable<int> Yetkiid { get; set; }
        [Display(Name ="Kullanıcı Adı")]
        [Required(ErrorMessage ="**Kullanıcı Adı Alanı Boş Bırakılamaz.")]
        public string Kullaniciadi { get; set; }
        [Display(Name = "Ad Soyad")]
        [Required(ErrorMessage = "**Ad Soyad Alanı Boş Bırakılamaz.")]
        public string AdSoyad { get; set; }
        [Display(Name = "E-mail")]
        [Required(ErrorMessage = "**E-mail Alanı Boş Bırakılamaz.")]
        public string Email { get; set; }
        [Display(Name = "Doğum Tarihi")]
        [Required(ErrorMessage = "**Doğum Tarihi Alanı Boş Bırakılamaz.")]
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        [Display(Name = "Üye Fotoğrafı")]
        public string Foto { get; set; }
        [Display(Name = "Şifre")]
        [Required(ErrorMessage = "**Şifre Alanı Boş Bırakılamaz.")]
        public string Sifre { get; set; }
    }
}
